class AppTexts {
  const AppTexts._();

  static const heyHalal = 'Hey Halal,';
  static const username = 'Username';
  static const changeLanguage = 'Change Language';
  static const settings = 'Settings';
  static const subTask = 'Sub - Task';
  static const account = 'Account';
  static const deleteTask = 'Delete Task';
  static const taskPriority = 'Task Priority :';
  static const taskCategory = 'Task Category :';
  static const taskTime = 'Task Time :';
  static const takePicture = 'Take picture';
  static const upTodo = 'Uptodo';
  static const defaultText = 'Default';
  static const addSubText = 'Add Sub - Task';
  static const importFromGoogleDrive = 'Import from Google Drive';
  static const importFromGallery = 'Import from gallery';
  static const logOut = 'Log out';
  static const supportUs = 'Support US';
  static const faq = 'FAQ';
  static const edit = 'Edit';

  static const editTask = 'Edit Task';
  static const newPassword = 'Enter new password';
  static const newImage = 'Change account Image';
  static const oldPassword = 'Enter old password';
  static const helpFeedback = 'Help & Feedback';
  static const aboutUs = 'About US';
  static const accountImage = 'Change account Image';
  static const accountPassword = 'Change account password';
  static const accountName = 'Change account name';
  static const appSettings = 'App Settings';
  static const tasksLeft = '10 Task left';
  static const tasksDone = '5 Task done';
  static const usernameExample = 'Martha Hays';
  static const chooseIconFromLibrary = 'Choose icon from library';
  static const categoryName = 'Category name :';
  static const categoryIcon = 'Category icon :';
  static const categoryColor = 'Category color :';
  static const createNewCategory = 'Create new Category';
  static const createCategory = 'Create Category';
  static const description = 'Descrtiption';
  static const profile = 'Profile';
  static const chooseCategory = 'Choose Category';
  static const addCategory = 'Add Category';
  static const university = 'University';
  static const close = 'Close';
  static const save = 'Save';
  static const cancel = 'Cancel';
  static const homeTitle = 'What do you want to do today?';
  static const homeSubTitle = 'Tap + to add your tasks';
  static const or = 'or';
  static const addTask = 'Add Task';
  static const index = 'Index';
  static const calendar = 'Calendar';
  static const confirmPassword = 'Confirm Password';
  static const dontHaveAnAccount = 'Don’t have an account? ';
  static const passwordHintText = '* * * * * * * * * * * *';
  static const password = 'Password';
  static const register = 'Register';
  static const registerGoogle = 'Register with Google';
  static const registerApple = 'Register with Apple';
  static const haveAccount = 'Already have an account?';
  static const appName = 'UpTodo';
  static const loginGoogle = 'Login with Google';
  static const loginApple = 'Login with Apple';
  static const login = 'Login';
  static const enterYourUsername = 'Enter your Username';
  static const skip = 'SKIP';
  static const next = 'NEXT';
  static const getStarted = 'GET STARTED';
  static const organizeYourTasks = 'Organize your tasks';
  static const organizeYourTasksSub =
      'You can organize your daily tasks by \n adding your tasks into separate categories';
  static const back = 'BACK';
  static const createDailyRoutine = 'Create daily routine';
  static const createDailyRoutineSub =
      'In Uptodo  you can create your\npersonalized routine to stay productive';
  static const manageYourTasks = 'Manage your tasks';
  static const manageYourTasksSubText =
      'You can easily manage all of your daily\ntasks in DoMe for free';
}
